//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salaros.vTiger.WebService.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salaros.vTiger.WebService.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;success&quot;:true, &quot;result&quot;: {&quot;label&quot;:&quot;Contacts&quot;,&quot;name&quot;:&quot;Contacts&quot;,&quot;createable&quot;:true,&quot;updateable&quot;:true,&quot;deleteable&quot;:true,&quot;retrieveable&quot;:true,&quot;fields&quot;:[{&quot;name&quot;:&quot;salutationtype&quot;,&quot;label&quot;:&quot;Salutation&quot;,&quot;mandatory&quot;:false,&quot;type&quot;:{&quot;picklistValues&quot;:[{&quot;label&quot;:&quot;--None--&quot;,&quot;value&quot;:&quot;--None--&quot;},{&quot;label&quot;:&quot;Mr.&quot;,&quot;value&quot;:&quot;Mr.&quot;},{&quot;label&quot;:&quot;Ms.&quot;,&quot;value&quot;:&quot;Ms.&quot;},{&quot;label&quot;:&quot;Mrs.&quot;,&quot;value&quot;:&quot;Mrs.&quot;},{&quot;label&quot;:&quot;Dr.&quot;,&quot;value&quot;:&quot;Dr.&quot;},{&quot;label&quot;:&quot;Prof.&quot;,&quot;value&quot;:&quot;Prof.&quot;}],&quot;defaultValue&quot;:&quot;--None--&quot;,&quot;name&quot;:&quot;picklist&quot;},&quot;nullable&quot;:true,&quot;editable&quot;:true [rest of string was truncate....
        /// </summary>
        internal static string MODULE_DESCRIBE_JSON {
            get {
                return ResourceManager.GetString("MODULE_DESCRIBE_JSON", resourceCulture);
            }
        }
    }
}
